

image:
  repository: kumaresh11/kubetest
  pullPolicy: IfNotPresent
  tag: kube
imagePullSecrets:
  - name: docker-secret


mysql:
  rootPassword: my-secret-pw
  database: testdb

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: False
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 90


