apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: mysql-data
          emptyDir: {}
        - name: php-index
          configMap:
            name: php-index
        - name: nginx-conf
          configMap:
            name: nginx-config

      initContainers:
        - name: init-php
          image: busybox
          command: ['sh', '-c', 'cp /config/index.php /shared/index.php']
          volumeMounts:
            - name: shared-data
              mountPath: /shared
            - name: php-index
              mountPath: /config

      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data

        - name: php
          image: php:8.1-fpm-bullseye
          command: ["sh", "-c"]
          args:
            - apt-get update && apt-get install -y libmysqli-dev default-mysql-client \
              && docker-php-ext-install mysqli && php-fpm
          volumeMounts:
            - mountPath: /var/www/html
              name: shared-data

        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: shared-data
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              name: nginx-conf
